"""Package existing aggregate evidence; do not train or read target arrays."""
import argparse
import copy
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import zipfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from scripts.build_m3w_evidence_manuscript_v2 import (
    ARMS, CONTRASTS, OUTPUT, SOURCES, build, load_sources, pointer,
)
from src.evaluation.m3w_portable_evidence import FALSE_CLAIMS, SCOPE, reconstruct, outputs

REPORT = ROOT / "outputs/publication_readiness_2026_09/blinded_reproduction_v1"
ARCHIVE = ROOT / "data/stage_cvpr2027_experiments/blinded_reproduction_v1/evidence_bundle.zip"
RUNNER = ROOT / "src/evaluation/m3w_portable_evidence.py"
PRIVATE_MARKERS = ("/users/", "/home/", "yangyue", "phdleyang", "world-model.git",
                   "m3w", "kcl.ac.uk", "king's college", "hpc.create", "ssh-rsa", "private key")

README = """# Aggregate Evidence Reproduction Draft

This package reconstructs existing development tables without the authors'
workspace, raw trajectories, model weights, network access or third-party Python
packages. It is not a model release or an independently confirmed result.

## Run

Use Python 3.10 or later. From the extracted directory:

```text
python3 -I -S reproduce.py --verify --output reproduced
```

The command checks file hashes, recomputes equal-site gains and worst-site/seed
easy degradation, and writes seven outputs. It refuses existing output files;
use a new output directory to repeat. No dependency installation is needed.
The two figures are frozen reference figures, hash-checked, not regenerated by
this entrypoint. No training or new bootstrap is performed.

## What Is Reproduced

Eight policies, 32 site summaries, 96 site/seed summaries, fourteen paired
contrasts and three causal joint-support summaries. Inputs are selected aggregate
fields from completed experiments, not the already-formatted output tables.
Coordinates remain annotation pixels. The task is eight observed and twelve
predicted annotation steps, stride twelve; no seconds or metric claim is made.
Forecast candidates are EqMotion-based ramp interventions relative to causal CV.

Both original primary superiority comparisons failed. A positive same-count
diagnostic does not replace either primary result. The archived 3,000-resample
intervals condition on four explored physical sites, not an untouched test set.
Three training seeds do not add independent sites. Missing-label easy safety
remains unverified; the 2% ADE ceiling is not a probability-of-harm guarantee.
Joint-support counts are proxy opportunities, not forecasting gains.

## What Is Not Reproduced

Raw-data conversion, forecasting, checkpoint replay, cost-head fitting, data-use
approval, independent calibration, final confirmation and full scientific
replication require separate data and experiment artifacts. No such files are
included or silently fetched. This is numerical reporting reproducibility only.
The schema preserves negative results and the unresolved scientific claims.
The figures/tables may be recognizable from earlier public research records.

## Review Boundary

Direct author identifiers, local paths and repository links have been removed
by an allowlisted export; this does not guarantee anonymity against recognition
or search, nor compliance with a conference's final submission policy. A final
human review and the venue's current rules are still required. This draft has
not been submitted. File hashes detect accidental changes, not malicious changes
to both payload and manifest. No raw or third-party data/code is redistributed.
"""


def digest(data):
    return hashlib.sha256(data).hexdigest()


def json_bytes(value):
    return (json.dumps(value, indent=2, allow_nan=False)+"\n").encode()


def reduce_metric(value):
    fields = ("coordinate_unit", "expected_scenes", "equal_scene_gain_percent",
              "scene_bootstrap_ci95", "bootstrap_resamples", "bootstrap_unit")
    row_fields = ("rows", "model_error", "reference_error", "gain_percent",
                  "model_p95", "model_p99", "reference_p95")
    result = {key: copy.deepcopy(value[key]) for key in fields}
    result["by_scene"] = {site: {key: row[key] for key in row_fields}
                          for site, row in value["by_scene"].items()}
    return result


def extract(docs):
    policies = []
    for arm, label in ARMS:
        source = docs["fraction_square_v1"]["summaries"][arm]
        summary = {key: reduce_metric(source[key]) for key in ("ADE", "FDE")}
        summary["subsets"] = {key: reduce_metric(source["subsets"][key])
                              for key in ("positive_easy", "hard")}
        summary["seeds"] = {}
        for seed, value in source["seeds"].items():
            summary["seeds"][seed] = dict(ADE=reduce_metric(value["ADE"]),
                subsets={"positive_easy": reduce_metric(value["subsets"]["positive_easy"])},
                **{k: value[k] for k in ("selected", "selected_unknown", "selected_incomplete", "zero_CV_harmed")})
        policies.append(dict(arm=arm, label=label, summary=summary))
    contrasts = []
    for label, name, path in CONTRASTS:
        value = pointer(docs[name], path)
        contrasts.append(dict(label=label, **{k: copy.deepcopy(value[k]) for k in (
            "scene_differences_pp", "mean_gain_difference_pp", "ci95_pp", "resamples", "unit")}))
    original = build(docs)
    support = [{k: v for k, v in row.items() if k not in ("source", "json_pointer")}
               for row in original["joint_support"]]
    return dict(schema_version=1, scope=SCOPE, policies=policies, contrasts=contrasts,
        joint_support=support, input_origin="hash_verified_archived_aggregate_excerpts",
        **{k: False for k in FALSE_CLAIMS})


def check_equivalence(result, original):
    """Every portable numeric/output field must match the frozen manuscript export."""
    fields = ("rows", "site_metrics", "site_seed_metrics", "contrasts", "joint_support")
    compared = 0
    for field in fields:
        if len(result[field]) != len(original[field]):
            raise ValueError("Changed export population")
        for got, expected in zip(result[field], original[field]):
            for key, value in got.items():
                if key not in expected or value != expected[key]:
                    raise ValueError(f"Changed manuscript field: {field}/{key}")
                compared += 1
    return compared


def scan_files(files):
    for name, data in files.items():
        path = Path(name)
        if path.is_absolute() or ".." in path.parts or path.suffix not in (".py", ".json", ".md", ".csv", ".svg"):
            raise ValueError(f"Disallowed archive member: {name}")
        text = data.decode("utf-8").lower()
        if any(marker in (name.lower()+"\n"+text) for marker in PRIVATE_MARKERS):
            raise ValueError(f"Direct identity or private path in package: {name}")
        if len(data) > 1_000_000:
            raise ValueError("Unexpectedly large aggregate artifact")


def make_files(docs):
    evidence = extract(docs)
    result = reconstruct(evidence)
    count = check_equivalence(result, build(docs))
    generated = {name: value.encode() for name, value in outputs(result).items()}
    files = {"reproduce.py": RUNNER.read_bytes(), "README.md": README.encode(),
             "evidence.json": json_bytes(evidence),
             **{"expected/"+name: data for name, data in generated.items()}}
    for name in ("risk_tradeoff.svg", "paired_contrasts.svg"):
        files["figures/"+name] = (ROOT / OUTPUT / name).read_bytes()
    scan_files(files)
    manifest = dict(schema_version=1, package_scope="deidentified_aggregate_reproduction_draft",
        files={name: dict(sha256=digest(data), bytes=len(data)) for name, data in sorted(files.items())},
        expected_outputs={name: digest(data) for name, data in generated.items()},
        anonymity_certified=False, full_training_reproduction=False,
        independent_confirmation=False, submission_ready=False)
    files["manifest.json"] = json_bytes(manifest)
    scan_files(files)
    return files, count


def archive_bytes(files):
    import io
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_STORED) as archive:
        for name, data in sorted(files.items()):
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            archive.writestr(info, data)
    return buffer.getvalue()


def clean_run(archive_path):
    """Execute extracted code using -I and audit hooks restricting file/network access."""
    with tempfile.TemporaryDirectory(prefix="evidence-clean-") as tmp:
        root = Path(tmp).resolve()
        package, runtime = root / "artifact", root / "runtime"
        package.mkdir()
        runtime.mkdir()
        with zipfile.ZipFile(archive_path) as archive:
            for member in archive.infolist():
                path = Path(member.filename)
                if path.is_absolute() or ".." in path.parts or (member.external_attr >> 16) & 0o170000 != 0o100000:
                    raise ValueError("Unsafe archive member")
            archive.extractall(package)
        # Allowed roots are extracted files and the interpreter installation, never the repository.
        wrapper = '''import json, os, pathlib, runpy, sys, sysconfig
root = pathlib.Path(sys.argv[1]).resolve()
installation = [pathlib.Path(sys.base_prefix).resolve(), pathlib.Path(sys.prefix).resolve()]
installation += [pathlib.Path(sysconfig.get_path(k)).resolve() for k in ("stdlib", "platstdlib")]
reads = set()
def guard(event, args):
    if event.startswith("socket.") or event in ("subprocess.Popen", "os.system"):
        raise RuntimeError("Network/subprocess access forbidden in aggregate reproduction")
    if event == "open" and not isinstance(args[0], int):
        p = pathlib.Path(args[0]).resolve()
        mode, flags = args[1], args[2]
        writing = (isinstance(mode, str) and any(c in mode for c in "wax+")) or (isinstance(flags, int) and flags & (os.O_WRONLY | os.O_RDWR | os.O_CREAT | os.O_TRUNC | os.O_APPEND))
        allowed = p.is_relative_to(root) or (not writing and any(p.is_relative_to(a) for a in installation))
        if not allowed:
            raise RuntimeError("File access outside extracted artifact/interpreter")
        if p.is_relative_to(root):
            reads.add(str(p.relative_to(root)))
sys.addaudithook(guard)
sys.argv = [str(root / "reproduce.py"), "--verify", "--output", str(root / "reproduced")]
runpy.run_path(str(root / "reproduce.py"), run_name="__main__")
print(json.dumps({"guarded_artifact_files_opened": sorted(reads)}))
'''
        env = dict(PATH=os.path.dirname(sys.executable)+":/usr/bin:/bin", HOME=str(runtime),
                   TMPDIR=str(runtime), PYTHONDONTWRITEBYTECODE="1", LC_ALL="C")
        process = subprocess.run([sys.executable, "-I", "-S", "-B", "-c", wrapper, str(package)],
            cwd=runtime, env=env, capture_output=True, text=True, timeout=120)
        if process.returncode:
            raise RuntimeError(f"Clean reproduction failed: {process.stderr}")
        lines = [json.loads(line) for line in process.stdout.splitlines()]
        manifest = json.loads((package / "manifest.json").read_text())
        reproduced = {path.name: digest(path.read_bytes()) for path in (package / "reproduced").iterdir()}
        if reproduced != manifest["expected_outputs"]:
            raise ValueError("Clean output hash mismatch")
        return dict(exit_code=process.returncode, python_version=sys.version.split()[0],
            isolated_interpreter=True, site_packages_disabled=True,
            temporary_home=True, file_access_guard=True,
            network_and_subprocess_guard=True, stdlib_only=True, output_hashes=reproduced,
            receipt=lines, stderr=process.stderr, guard_is_not_OS_sandbox=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    docs = load_sources(ROOT)
    files, values = make_files(docs)
    raw = archive_bytes(files)
    if args.verify:
        if ARCHIVE.read_bytes() != raw:
            raise ValueError("Archive differs from frozen source reconstruction")
    else:
        ARCHIVE.parent.mkdir(parents=True, exist_ok=True)
        with ARCHIVE.open("xb") as stream:
            stream.write(raw)
    run = clean_run(ARCHIVE)
    report = dict(result_source="fresh_packaging_and_isolated_aggregate_reproduction",
        archived_experiments="cached_verified", source_report_sha256=SOURCES,
        runner_sha256=digest(RUNNER.read_bytes()), archive_sha256=digest(raw),
        archive_bytes=len(raw), archive_members=len(files), matched_original_fields=values,
        payload={name: dict(bytes=len(data), sha256=digest(data)) for name, data in sorted(files.items())},
        clean_execution=run, direct_identity_scan="pass_fixed_marker_set_not_anonymity_guarantee",
        new_training=False, new_prediction_or_target_readout=False, new_bootstrap=False,
        independent_confirmation=False, full_training_reproduction=False,
        anonymous_submission_ready=False, submission_ready=False,
        stage5c_executed=False, smc_enabled=False)
    target = REPORT / "verification.json"
    text = json_bytes(report)
    if args.verify:
        if target.read_bytes() != text:
            raise ValueError("Fresh verification differs from saved receipt")
    else:
        REPORT.mkdir(parents=True, exist_ok=True)
        with target.open("xb") as stream:
            stream.write(text)
    print(json.dumps(dict(verified=args.verify, archive_bytes=len(raw), archive_members=len(files),
        matched_original_fields=values, clean_run_exit_code=run["exit_code"],
        output_files=len(run["output_hashes"]), submission_ready=False)))


if __name__ == "__main__":
    main()
