"""Submit one isolated fitting pilot or full paired training job, never duplicate."""
import argparse
from datetime import datetime, timezone
import hashlib
import json
import shlex
import subprocess
from scripts.prepare_m3w_create_runtime import ROOT, PRIVATE, HANDOFF


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--phase',choices=['pilot','train'],required=True)
    p.add_argument('--attempt',type=int,choices=range(1,4),default=1);a=p.parse_args()
    suffix='' if a.attempt==1 else '_attempt'+str(a.attempt)
    receipt=PRIVATE/('create_head_'+a.phase+'_submission'+suffix+'.json')
    for n in range(1,a.attempt):
        prev_suffix='' if n==1 else '_attempt'+str(n)
        prev=json.loads((PRIVATE/('create_head_'+a.phase+'_submission'+prev_suffix+'.json')).read_text())
        assert prev['response']['returncode'] in (255,None), 'Only a failed/unknown SSH attempt can be investigated again'
    if receipt.exists():
        raise ValueError('Existing or uncertain submission: inspect it, never duplicate')
    subprocess.run(['git','check-ignore','--quiet',str(receipt)],cwd=ROOT,check=True)
    manifest=json.loads((PRIVATE/'remote_input_manifest.json').read_text());home=manifest['remote_path']
    assert len(manifest['groups'])==108 and not manifest['held_rows_transferred']
    flags='--pilot' if a.phase=='pilot' else '--resume'
    walltime='02:00:00' if a.phase=='pilot' else '08:00:00'
    script=f'''#!/bin/bash -l
#SBATCH --job-name=m3w_easy_head_{a.phase}
#SBATCH --partition=cpu
#SBATCH --account=kcl
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --time={walltime}
#SBATCH --output={a.phase}-%j.out
#SBATCH --error={a.phase}-%j.err
set -euo pipefail
test -n "${{SLURM_JOB_ID:-}}"
cd "${{SLURM_SUBMIT_DIR}}"
module load python/3.11.6-gcc-13.2.0
export PYTHONDONTWRITEBYTECODE=1 PYTHONNOUSERSITE=1
export OMP_NUM_THREADS=4 OPENBLAS_NUM_THREADS=4 MKL_NUM_THREADS=4 NUMEXPR_NUM_THREADS=4
unset PYTHONPATH
../easy_hurdle_runtime_v2/venv/bin/python code/scripts/train_m3w_easy_hurdle_portable.py --home "$PWD" {flags}
'''
    code=r'''
import hashlib,json,pathlib,subprocess,sys
p=json.loads(sys.stdin.read());home=pathlib.Path(p['home']);phase=p['phase'];assert phase in ('pilot','train')
assert json.loads((home/'.owner.json').read_text())['experiment']=='european_easy_hurdle_v1'
manifest=json.loads((home/'input_manifest.json').read_text());assert len(manifest['groups'])==108 and not manifest['held_rows_transferred']
assert hashlib.sha256((home/'input_manifest.json').read_bytes()).hexdigest()==p['manifest_sha256']
if phase=='train':
    pilot=json.loads((home/'pilot.json').read_text());assert pilot['pilot'] and pilot['groups']==1 and not pilot['held_outcomes_used']
    assert pilot['manifest_sha256']==p['manifest_sha256']
    result=subprocess.run(['sacct','-j',pilot['environment']['job_id'],'-X','--noheader','--parsable2','--format=State,ExitCode'],capture_output=True,text=True,timeout=20)
    assert result.returncode==0 and result.stdout.strip()=='COMPLETED|0:0','Successful real pilot required'
intent=home/('submit_'+phase+'_intent.json');done=home/('submit_'+phase+'_receipt.json')
assert not intent.exists() and not done.exists(),'Remote submission intent/receipt exists: do not resubmit; inspect it'
q=subprocess.run(['squeue','--me','-h','-o','%i|%j|%T'],capture_output=True,text=True,timeout=20)
assert q.returncode==0 and 'm3w_easy_head_' not in q.stdout,'Queue failed or fitting job exists'
script=home/('run_'+phase+'.sh');assert not script.exists();script.write_text(p['script'])
intent.write_text(json.dumps({'script_sha256':hashlib.sha256(script.read_bytes()).hexdigest(),'manifest_sha256':p['manifest_sha256']})+'\n')
r=subprocess.run(['sbatch','--parsable',script.name],cwd=home,capture_output=True,text=True,timeout=30)
out={'returncode':r.returncode,'stdout':r.stdout,'stderr':r.stderr,'phase':phase,'script_sha256':hashlib.sha256(script.read_bytes()).hexdigest()}
if r.returncode==0:
    job=r.stdout.strip().split(';')[0];assert job.isdigit();out['job_id']=job
done.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out))
'''
    ssh=json.loads((HANDOFF/'observations.json').read_text())['ssh_arguments']
    # Match the remote JSON bytes generated by the exporter's immutable write.
    remote_manifest={k:v for k,v in manifest.items() if k!='remote_path'}
    encoded=(json.dumps(remote_manifest,indent=2)+'\n').encode()
    payload=dict(home=home,phase=a.phase,script=script,manifest_sha256=hashlib.sha256(encoded).hexdigest())
    start=datetime.now(timezone.utc).isoformat()
    try:
        r=subprocess.run(ssh+[shlex.join(['/usr/bin/python3','-c',code])],input=json.dumps(payload),text=True,capture_output=True,timeout=60)
        response=dict(returncode=r.returncode,stdout=r.stdout,stderr=r.stderr)
    except subprocess.TimeoutExpired:
        response=dict(returncode=None,observation_timeout=True,retry_requires_remote_intent_inspection=True)
    record=dict(started_utc=start,completed_utc=datetime.now(timezone.utc).isoformat(),response=response,phase=a.phase,
        script_sha256=hashlib.sha256(script.encode()).hexdigest(),held_rows_used=False,simulation_touched=False,
        attempt=a.attempt,remote_no_intent_and_no_receipt_required_before_submit=True)
    with receipt.open('x') as f:
        f.write(json.dumps(record,indent=2)+'\n')
    print(json.dumps(dict(returncode=response['returncode'],phase=a.phase,receipt_sha256=hashlib.sha256(receipt.read_bytes()).hexdigest())))


if __name__=='__main__':
    main()
